/**
 * Card Data — Hermetic Flight Tarot
 *
 * 78 cards parsed from operator-provided CSV.
 * Source: src/data/Card Meanings with Aerial Correlation.xlsx - Sheet1.csv
 *
 * journalingPrompt values are AI-generated placeholders.
 * Operator review recommended before launch.
 */

export interface CardData {
  /** URL-safe slug for image paths and share URLs (e.g. 'the-fool') */
  slug: string;
  /** Display name (e.g. 'The Fool') */
  name: string;
  /** Core meaning of the card */
  meaning: string;
  /** How this card connects to aerial circus / performance themes */
  aerialConnection: string;
  /** Open-ended journaling prompt for the reader */
  journalingPrompt: string;
  /**
   * True once card art PNG is at /public/images/cards/[slug].png.
   * Controls pre- vs post-reveal rendering.
   */
  artReady: boolean;
}

export const CARDS: CardData[] = [
  // -------------------------------------------------------------------------
  // Major Arcana (22 cards)
  // -------------------------------------------------------------------------
  {
    slug: 'the-fool',
    name: 'The Fool',
    meaning: 'new beginnings, innocence, spontaneity, and a "leap of faith" into the unknown',
    aerialConnection: 'Playful, whimsical, and childlike, white for innocence, flowers for new beginnings, flute for playful energy',
    journalingPrompt: 'What would you begin today if you allowed yourself to not know how it ends?',
    artReady: false,
  },
  {
    slug: 'the-magician',
    name: 'The Magician',
    meaning: 'manifestation, willpower, and the ability to turn ideas into reality',
    aerialConnection: 'One arm up one arm down, symbolizing duality, green for manifestation and wealth energy',
    journalingPrompt: 'What resources do you already have that you have been treating as incomplete?',
    artReady: false,
  },
  {
    slug: 'the-high-priestess',
    name: 'The High Priestess',
    meaning: 'Intuition, subconscious, mystery, divine feminine.',
    aerialConnection: 'Elevated in intuition between duality of white and black, stars on her body for connection to the universe, full moon on her crown to connect with Hecate and lunar cycles, book for the book of knowledge, purple scepter for intuitive power, blue robe for subconscious mind',
    journalingPrompt: 'What have you been sensing that you have not yet allowed yourself to trust?',
    artReady: false,
  },
  {
    slug: 'the-empress',
    name: 'The Empress',
    meaning: 'Abundance, fertility, nurturing, creativity.',
    aerialConnection: 'Circle of life and fertility- Lyra, green fertility, fire- abundance, action energy, red lips - symbolize pomegranates',
    journalingPrompt: 'Where in your life are you withholding nurturing from yourself while freely giving it to others?',
    artReady: false,
  },
  {
    slug: 'the-emperor',
    name: 'The Emperor',
    meaning: 'Structure, authority, stability, patriarch.',
    aerialConnection: 'Authoritative stance, elevated in power, red for raw passion, action,  power',
    journalingPrompt: 'What would you build differently if you led from wisdom rather than the need to be obeyed?',
    artReady: false,
  },
  {
    slug: 'the-hierophant',
    name: 'The Hierophant',
    meaning: 'Tradition, conformity, spiritual guidance, education.',
    aerialConnection: 'Inverted to offer enlightenment and new knowledge, book is knowledge, white is represents spiritual purity, holiness, and clear, structured beliefs, red for passion, blue for emotional clarity',
    journalingPrompt: 'Which traditions are you honoring by choice, and which are you following out of habit or fear?',
    artReady: false,
  },
  {
    slug: 'the-lovers',
    name: 'The Lovers',
    meaning: 'Relationships, alignment, choices, harmony.',
    aerialConnection: 'love is love, positioning mirrors the higher self, white and black balancing masculine and feminine, partnership, choosing',
    journalingPrompt: 'What choice are you avoiding right now, and what does that avoidance tell you about your values?',
    artReady: false,
  },
  {
    slug: 'the-chariot',
    name: 'The Chariot',
    meaning: 'Willpower, victory, focus, determination.',
    aerialConnection: 'Determined stance in the Lyra to appear as though driving a chariot, dress represents intellect and optimism',
    journalingPrompt: 'What goal are you pursuing with discipline, and what would it mean to finally reach it?',
    artReady: false,
  },
  {
    slug: 'strength',
    name: 'Strength',
    meaning: 'Courage, persuasion, influence, inner strength.',
    aerialConnection: 'dragon staff is akin to a lion, dress symbolizing spiritual wisdom and internal strength, stance represents stability and relying on inner strength',
    journalingPrompt: 'When have you met a difficult situation with gentleness rather than force, and what did that cost you?',
    artReady: false,
  },
  {
    slug: 'the-hermit',
    name: 'The Hermit',
    meaning: 'Introspection, solitude, guidance, soul-searching.',
    aerialConnection: 'perched high up in the silks looking out into the darkness to symbolize searching within, colors representing wisdom, the subconscious, and solitude.',
    journalingPrompt: 'What truth have you been searching for in the outer world that you quietly suspect you already know within?',
    artReady: false,
  },
  {
    slug: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    meaning: 'Cycles, luck, change, destiny.',
    aerialConnection: 'Sun wheel spinning symbolizes inevitable cycles, the energy of intellect and the illuminating power of understanding, black lace to represent the intricisies and vastness of the universe and subconscious mind',
    journalingPrompt: 'What cycle in your life is completing right now, and what are you being invited to release?',
    artReady: false,
  },
  {
    slug: 'justice',
    name: 'Justice',
    meaning: 'Fairness, truth, cause and effect, law.',
    aerialConnection: 'red on the sword to represent passion and power to enact justice, yellow to highlight mental energy and rational thought, pole to symbolize stability and scales for balance. Piercing gaze seeking the truth',
    journalingPrompt: 'Where in your life are you asking for fairness while not yet fully seeing your own role in the situation?',
    artReady: false,
  },
  {
    slug: 'the-hanged-man',
    name: 'The Hanged Man',
    meaning: 'Surrender, new perspective, letting go, patience.',
    aerialConnection: 'An ankle hang in Spanish web signifies surrender, new perspectives, crown to represent enlightenment, gold shorts highlighting divine wisdom',
    journalingPrompt: 'What would shift in your understanding if you were willing to see this situation from an entirely different angle?',
    artReady: false,
  },
  {
    slug: 'death',
    name: 'Death',
    meaning: 'Endings, transformation, transition, rebirth.',
    aerialConnection: 'black for endings, white rose for purity of the soul and transformation, purple for alchemy, transition, and intuition, suspended in shibari to represent the transition from earth to another realm',
    journalingPrompt: 'What part of your identity is ready to be released so that something truer can take its place?',
    artReady: false,
  },
  {
    slug: 'temperance',
    name: 'Temperance',
    meaning: 'Balance, moderation, patience, purpose.',
    aerialConnection: 'deep split to represent balance, white to symbolize, white for purity, blue for emotions and subconscious',
    journalingPrompt: 'Where are you pushing too hard or holding back too much, and what would balance actually feel like there?',
    artReady: false,
  },
  {
    slug: 'the-devil',
    name: 'The Devil',
    meaning: 'Materialism, addiction, bondage, shadow self.',
    aerialConnection: 'the apple to represent the tree of knowledge and the first "sin", shibari to represent being bound and trapped, inverted cross to represent deviance, fire to represent hellfire',
    journalingPrompt: 'What pattern keeps pulling you back even when you know it no longer serves you?',
    artReady: false,
  },
  {
    slug: 'the-tower',
    name: 'The Tower',
    meaning: 'Sudden change, upheaval, revelation, chaos.',
    aerialConnection: 'black represents unknown, grey represents outdated thoughts and crumbling beliefs, falling pose symbolizes the tower actually toppling.',
    journalingPrompt: 'What structure in your life are you maintaining that has already begun to crack?',
    artReady: false,
  },
  {
    slug: 'the-star',
    name: 'The Star',
    meaning: 'Hope, faith, rejuvenation, inspiration.',
    aerialConnection: 'Gold represents divine guidance, tipped hoop symbolizes subconscious mind, green represents fertility and abundance, free hanging representing hope',
    journalingPrompt: 'What does hope feel like in your body right now, and where are you resisting it?',
    artReady: false,
  },
  {
    slug: 'the-moon',
    name: 'The Moon',
    meaning: 'Illusion, fear, anxiety, intuition.',
    aerialConnection: 'grey represents intuition, white represents spiritual connections, blue crown represents emotions, spider represents divine feminine energy,',
    journalingPrompt: 'What fear has been distorting your perception lately, and what might be true beneath it?',
    artReady: false,
  },
  {
    slug: 'the-sun',
    name: 'The Sun',
    meaning: 'Joy, success, vitality, positivity.',
    aerialConnection: 'Gold represents joy, happiness, red represents vitality and action, the scepter represents confidence and courage ,the crown symbolizes sun rays- confidence, clarity. Elbow hang represents strength and vitality',
    journalingPrompt: 'What brings you genuine, uncomplicated joy, and how much room are you making for it right now?',
    artReady: false,
  },
  {
    slug: 'judgement',
    name: 'Judgement',
    meaning: 'Reflection, awakening, absolution, decision.',
    aerialConnection: 'Ballerina pose to represent moving forward, vulnerable people in front to represent trusting in judgement to lead to our highest good, horn as a call to action, white wings to represent purity, people recieving the message on the earth, blue for deep subconscious',
    journalingPrompt: 'What would you choose differently if you truly believed you had already been forgiven for the past?',
    artReady: false,
  },
  {
    slug: 'the-world',
    name: 'The World',
    meaning: 'Completion, fulfillment, travel, harmony.',
    aerialConnection: 'Purple Symbolizes spiritual attainment, divinity, wisdom, gold Represents enlightenment, joy, and the energy of the universe, pole represents the grounded energy of earth',
    journalingPrompt: 'What in your current chapter is asking to be recognized as complete before you move to the next?',
    artReady: false,
  },

  // -------------------------------------------------------------------------
  // Minor Arcana — Torches (14 cards)
  // -------------------------------------------------------------------------
  {
    slug: 'ace-of-torches',
    name: 'Ace of Torches',
    meaning: 'Inspiration, creative spark, new ventures',
    aerialConnection: 'forward motion in stance, red for action and vitality energy',
    journalingPrompt: 'What creative idea has been sparking inside you that you have not yet given permission to begin?',
    artReady: false,
  },
  {
    slug: '2-of-torches',
    name: '2 of Torches',
    meaning: 'Planning, decisions between paths, personal power',
    aerialConnection: 'one torch up and one torch down to symbolize choosing between two paths, confident expression for personal power, red for action energy',
    journalingPrompt: 'What two directions are you weighing, and which one feels most aligned with who you are becoming?',
    artReady: false,
  },
  {
    slug: '3-of-torches',
    name: '3 of Torches',
    meaning: 'Expansion abroad, foresight, trade/exploration',
    aerialConnection: 'looking off into distance eluding to exploration, red for action energy, fan raised above head for expansion and foresight',
    journalingPrompt: 'What horizon are you scanning, and what would it take for you to trust your vision enough to move toward it?',
    artReady: false,
  },
  {
    slug: '4-of-torches',
    name: '4 of Torches',
    meaning: 'Celebration, homecoming, harmony, stability achieved',
    aerialConnection: 'A couple representing union, stability and harmony, one knee for stability, wide stance for stability, red color for passion, gold for joy',
    journalingPrompt: 'What milestone in your life deserves to be celebrated that you have been moving past without pausing to honor?',
    artReady: false,
  },
  {
    slug: '5-of-torches',
    name: '5 of Torches',
    meaning: 'Competition, struggle, disagreement, chaos',
    aerialConnection: 'fighting people depict confrontation, chaos, and tension, red for action and passion',
    journalingPrompt: 'Where is the conflict you are in right now actually a signal about something you deeply care about?',
    artReady: false,
  },
  {
    slug: '6-of-torches',
    name: '6 of Torches',
    meaning: 'Victory, recognition, public success, confidence',
    aerialConnection: 'body language depicts idolizing the person in the center for fame, success, and recognition energy, red for vitality and passion',
    journalingPrompt: 'What recognition would mean the most to you right now, and what stops you from claiming it?',
    artReady: false,
  },
  {
    slug: '7-of-torches',
    name: '7 of Torches',
    meaning: 'Defending position, standing ground, courage under pressure',
    aerialConnection: 'body language depicting rising above someone/something, stern face shows personal power, red for action and passion',
    journalingPrompt: 'What position or value are you being called to defend, and do you believe it is truly worth the fight?',
    artReady: false,
  },
  {
    slug: '8-of-torches',
    name: '8 of Torches',
    meaning: 'Swift action, movement, messages, fast progress',
    aerialConnection: 'fire hoop depict fast moving energy, red for action',
    journalingPrompt: 'What has been moving quickly in your life lately, and are you directing that momentum or just riding it?',
    artReady: false,
  },
  {
    slug: '9-of-torches',
    name: '9 of Torches',
    meaning: 'Resilience, persistence, last stand, nearly there',
    aerialConnection: 'body language depicting exhaustion but still the will to push through, resilience, fire on either side to depict resilience as well.',
    journalingPrompt: 'What are you still standing for even when you are tired, and what does that perseverance reveal about you?',
    artReady: false,
  },
  {
    slug: '10-of-torches',
    name: '10 of Torches',
    meaning: 'Burden, overwhelm, responsibility, carrying too much',
    aerialConnection: '5 pairs of arms and 10 flames to show carrying too much,',
    journalingPrompt: 'What are you carrying right now that was never yours to carry, and what would it feel like to set it down?',
    artReady: false,
  },
  {
    slug: 'page-of-torches',
    name: 'Page of Torches',
    meaning: 'Enthusiasm, new ideas, exploration, adventurous spirit',
    aerialConnection: 'gold for joy, single flame beheld in wonder to depict excitement for new things',
    journalingPrompt: 'What would you explore with pure curiosity if there were no pressure to already be good at it?',
    artReady: false,
  },
  {
    slug: 'knight-of-torches',
    name: 'Knight of Torches',
    meaning: 'Passion, impulsiveness, adventure, charming energy, rapid pursuit',
    aerialConnection: 'Flaming sword for action and rapid pursuit, red for action energy, green for a brave heart',
    journalingPrompt: 'Where is your passion driving you forward right now, and where might it be running ahead of your wisdom?',
    artReady: false,
  },
  {
    slug: 'queen-of-torches',
    name: 'Queen of Torches',
    meaning: 'Confidence, independence, determination, vibrant leadership, warmth',
    aerialConnection: 'blue for emotional mastery, stance calm and confidence to represent mastery of',
    journalingPrompt: 'How do you lead in your own life, and where are you being called to show up with more warmth and fire?',
    artReady: false,
  },
  {
    slug: 'king-of-torches',
    name: 'King of Torches',
    meaning: 'Visionary leadership, entrepreneurial, bold, charismatic authority',
    aerialConnection: 'Contact staff for adventure and rapid pursuit, red for action energy',
    journalingPrompt: 'What vision are you bold enough to pursue, and who else might be waiting for you to lead the way?',
    artReady: false,
  },

  // -------------------------------------------------------------------------
  // Minor Arcana — Cups (14 cards)
  // -------------------------------------------------------------------------
  {
    slug: 'ace-of-cups',
    name: 'Ace of Cups',
    meaning: 'New love, emotional opening, spiritual fulfillment',
    aerialConnection: 'Diving pose to embody white dove of divine inspiration and wisdom, pink to symbolize new love, Lyra to represent emotional fulfillment',
    journalingPrompt: 'What would you allow yourself to feel more fully if you trusted that your heart could hold it?',
    artReady: false,
  },
  {
    slug: '2-of-cups',
    name: '2 of Cups',
    meaning: 'Partnership, romantic connection, mutual attraction',
    aerialConnection: 'black and white to represent masculine and feminine, cradled in Lyra together to depict mutual connection and devotion',
    journalingPrompt: 'What connection in your life is asking for more presence and less performance from you?',
    artReady: false,
  },
  {
    slug: '3-of-cups',
    name: '3 of Cups',
    meaning: 'Celebration, friendship, community joy',
    aerialConnection: '3 women representing community and joy, flowers for new life, green abundance and love, blue emotional fulfillment, orange joy and enthusiasm',
    journalingPrompt: 'Who are the people in your life whose company genuinely restores you, and when did you last let yourself be fully present with them?',
    artReady: false,
  },
  {
    slug: '4-of-cups',
    name: '4 of Cups',
    meaning: 'Apathy, contemplation, dissatisfaction despite having much',
    aerialConnection: 'elbow hang in small Lyra to depict lack of emotional fulfillment in spite of opportunity, forlorn expression for apathy, black for dark night of the soul',
    journalingPrompt: 'What gift or opportunity is sitting in front of you right now that you have been looking past?',
    artReady: false,
  },
  {
    slug: '5-of-cups',
    name: '5 of Cups',
    meaning: 'Loss, grief, disappointment, focusing on negative',
    aerialConnection: 'elbow hang in big Lyra to depict immense grief, black for greif',
    journalingPrompt: 'What loss are you still carrying, and what would it mean to grieve it fully rather than just surviving it?',
    artReady: false,
  },
  {
    slug: '6-of-cups',
    name: '6 of Cups',
    meaning: 'Nostalgia, innocence, childhood memories, reunion',
    aerialConnection: 'Back balance in mini Lyra to depict safety and familiarity, white for purity and innocence of childhood',
    journalingPrompt: 'What memory from your past holds a quality of being that your present life is longing for?',
    artReady: false,
  },
  {
    slug: '7-of-cups',
    name: '7 of Cups',
    meaning: 'Illusion, choices, fantasies, scattered energy',
    aerialConnection: 'reclined body to show a day dreaming, blue for dreams and illusion',
    journalingPrompt: 'Which of the possibilities you are imagining is truly calling you, and which ones are just beautiful distractions?',
    artReady: false,
  },
  {
    slug: '8-of-cups',
    name: '8 of Cups',
    meaning: 'Walking away, abandonment, emotional withdrawal, seeking deeper meaning',
    aerialConnection: 'split away from pov to show abandonment, emotional withdrawal, white for',
    journalingPrompt: 'What are you ready to walk away from, even though part of you still wants it to have been enough?',
    artReady: false,
  },
  {
    slug: '9-of-cups',
    name: '9 of Cups',
    meaning: 'Contentment, satisfaction, wish fulfillment, emotional abundance',
    aerialConnection: 'deep arch over Lyra to show abundance and joy, rainbow costume for wish fulfillment',
    journalingPrompt: 'If you allowed yourself to feel truly satisfied with where you are right now, what would that actually look and feel like?',
    artReady: false,
  },
  {
    slug: '10-of-cups',
    name: '10 of Cups',
    meaning: 'Emotional fulfillment, happy family, lasting happiness, harmony',
    aerialConnection: 'expecting mother and father to depict emotional fulfillment and marital bliss, mother cradled in hoop for emotional fullfillment, rainbow on her dress to show wish fulfillment, father watching over his partner for harmony and protection',
    journalingPrompt: 'What does a truly fulfilled life look like to you, and how close are you to living it?',
    artReady: false,
  },
  {
    slug: 'page-of-cups',
    name: 'Page of Cups',
    meaning: 'Emotional curiosity, creative beginning, gentle invitation, intuitive messages',
    aerialConnection: 'blue for emotional curiosity, wine glass pose for inviting intuition, joy in facial expression to show emotional connection to new beginnings',
    journalingPrompt: 'What gentle feeling or intuitive nudge have you been dismissing as too small to take seriously?',
    artReady: false,
  },
  {
    slug: 'knight-of-cups',
    name: 'Knight of Cups',
    meaning: 'Romance, charm, idealism, emotional offers, artistic pursuit',
    aerialConnection: 'inviting pose for welcoming energy',
    journalingPrompt: 'Where in your life are you being invited to lead with your heart even when your head has reservations?',
    artReady: false,
  },
  {
    slug: 'queen-of-cups',
    name: 'Queen of Cups',
    meaning: 'Compassion, intuition, emotional maturity, nurturing love, psychic sensitivity',
    aerialConnection: 'green for nurture, woman on the moon pose for emotional intelligence, pelvis necklace for emotional mastery and manifestation energy',
    journalingPrompt: 'How do you care for others from a full cup, and when does your compassion come at the cost of your own wellbeing?',
    artReady: false,
  },
  {
    slug: 'king-of-cups',
    name: 'King of Cups',
    meaning: 'Emotional balance, diplomatic, compassionate leadership, wise counselor',
    aerialConnection: 'green abundance, blue clear communication of emotions and thoughts, red for action and passion, bones',
    journalingPrompt: 'When you are at your most emotionally grounded, what kind of leader and presence do you become?',
    artReady: false,
  },

  // -------------------------------------------------------------------------
  // Minor Arcana — Swords (14 cards)
  // -------------------------------------------------------------------------
  {
    slug: 'ace-of-swords',
    name: 'Ace of Swords',
    meaning: 'Mental clarity, breakthrough, truth revealed',
    aerialConnection: 'Mask resembles truth revealed, white for clarity and truth, fog for illusions falling away, honey comb and bee for new beginnings and honesty',
    journalingPrompt: 'What truth have you recently come to see clearly, and what does it ask of you now that you see it?',
    artReady: false,
  },
  {
    slug: '2-of-swords',
    name: '2 of Swords',
    meaning: 'Difficult choice, stalemate, avoidance of truth',
    aerialConnection: 'Blindfolded for lack of clarity, silks crossed to symbolize cross roads, feet pointed in two different directions to show indecision, blue for internernal wisdom (third eye), purple for divine wisdom and contemplation',
    journalingPrompt: 'What decision are you stalling on, and what information are you afraid of receiving that would force you to choose?',
    artReady: false,
  },
  {
    slug: '3-of-swords',
    name: '3 of Swords',
    meaning: 'Heartbreak, sorrow, painful separation',
    aerialConnection: 'red scarf to symbolize heart ache, white representing hope, pose depicting moving on through grief and healing through trauma.',
    journalingPrompt: 'What heartbreak are you still carrying, and what would it mean to let it be part of your story without letting it define you?',
    artReady: false,
  },
  {
    slug: '4-of-swords',
    name: '4 of Swords',
    meaning: 'Rest, recovery, temporary truce, meditation',
    aerialConnection: 'Reclined position to reflect resting, being held in the air to symbolize truce and metaphorical death pff "suspended animation", eyes closed for introspection, Yellow/Gold: Divine, enlightened, conscious, active mind, healing energy,',
    journalingPrompt: 'What are you refusing to rest from, and what would become possible if you gave yourself real permission to stop?',
    artReady: false,
  },
  {
    slug: '5-of-swords',
    name: '5 of Swords',
    meaning: 'Defeat, betrayal, harsh victory, dishonor',
    aerialConnection: 'deep blue represents internal conflict, splits up high reflects solitary victory, person walking away shows defeat',
    journalingPrompt: 'When have you won something at the cost of a relationship or your integrity, and what did that teach you?',
    artReady: false,
  },
  {
    slug: '6-of-swords',
    name: '6 of Swords',
    meaning: 'Transition, moving forward, recovery, journey to calmer waters',
    aerialConnection: 'physical position to represent the boat of passage and moving on, reclining to depict calm energy, sword in hand to remind it can be hard to see the bigger picture, white silks for hope',
    journalingPrompt: 'What difficult passage are you moving through right now, and what calmer shore are you moving toward?',
    artReady: false,
  },
  {
    slug: '7-of-swords',
    name: '7 of Swords',
    meaning: 'Deception, strategy, sneakiness, getting away with something',
    aerialConnection: 'position to depict avoiding conflict, yellow for mental energy involved, expression depicting pain of not facing your truth and running away,',
    journalingPrompt: 'Where are you avoiding a direct confrontation with yourself or someone else, and what is that costing you?',
    artReady: false,
  },
  {
    slug: '8-of-swords',
    name: '8 of Swords',
    meaning: 'Restriction, feeling trapped, victim mentality, self-imposed limitation',
    aerialConnection: 'Wrapped to depict feeling trapped by oneself, visible struggle, blue for unprocessed emotions',
    journalingPrompt: 'What story are you telling yourself about why you cannot move forward, and how much of it is actually true?',
    artReady: false,
  },
  {
    slug: '9-of-swords',
    name: '9 of Swords',
    meaning: 'Anxiety, worry, nightmares, mental anguish',
    aerialConnection: 'anxious expression for worry and mental anguish, self imposed binding from unprocessed trauma, red for action repressed energy',
    journalingPrompt: 'What are you most afraid of right now, and how much of that fear lives in your thoughts versus in reality?',
    artReady: false,
  },
  {
    slug: '10-of-swords',
    name: '10 of Swords',
    meaning: 'Rock bottom, ending, betrayal, painful conclusion',
    aerialConnection: 'Slumped over to represent immense pain of betrayal, rock bottom, red for love and beauty, nine swords hanging above to depict unresolved issued',
    journalingPrompt: 'What has finally ended that you kept trying to save, and what does its ending make room for?',
    artReady: false,
  },
  {
    slug: 'page-of-swords',
    name: 'Page of Swords',
    meaning: 'Vigilance, curiosity, mental agility, truth-seeking, messages of challenges',
    aerialConnection: 'position to depict awareness, assertiveness, expression to show truth seeking, purple for fast moving thoughts, silver for mental energy',
    journalingPrompt: 'What question are you most afraid to ask right now, and what might the honest answer reveal?',
    artReady: false,
  },
  {
    slug: 'knight-of-swords',
    name: 'Knight of Swords',
    meaning: 'Assertiveness, ambition, driven action, direct confrontation, rushing in',
    aerialConnection: 'Position to show driven action, armor for strength',
    journalingPrompt: 'Where are you charging forward with certainty, and what might you be missing by moving so fast?',
    artReady: false,
  },
  {
    slug: 'queen-of-swords',
    name: 'Queen of Swords',
    meaning: 'Perceptive, clear-minded, independent thinking, honest communication, direct truth',
    aerialConnection: 'Blue to depict intellect and conscious mind, Highlights the mental energy, alertness, and active, forward-looking nature of her decisions, knighting the man to represent clear communication',
    journalingPrompt: 'What truth do you know that you have been softening to protect others, and what would honest directness actually make possible?',
    artReady: false,
  },
  {
    slug: 'king-of-swords',
    name: 'King of Swords',
    meaning: 'Intellectual authority, logical, truth, ethical judgment, clear communication',
    aerialConnection: 'head hang for intellectual power, decision making, and ethical judgement, grey to symbolize neutrality',
    journalingPrompt: 'What decision are you being called to make with both clarity and fairness, even when it is uncomfortable?',
    artReady: false,
  },

  // -------------------------------------------------------------------------
  // Minor Arcana — Pentacles (14 cards)
  // -------------------------------------------------------------------------
  {
    slug: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    meaning: 'New financial opportunity, material manifestation, prosperity seed',
    aerialConnection: 'white to symbolize divine origin of the gift, low squat to symbolize root energy for manifestation of physical wealth',
    journalingPrompt: 'What new opportunity for material or creative growth is presenting itself, and what would it take to truly receive it?',
    artReady: false,
  },
  {
    slug: '2-of-pentacles',
    name: '2 of Pentacles',
    meaning: 'Juggling resources, adaptability, balance in change',
    aerialConnection: 'two flaming feet to show juggling responsibilities and action energy, position for balance, red for action and passion',
    journalingPrompt: 'What are you currently juggling, and where are you sacrificing sustainability for the appearance of having it all together?',
    artReady: false,
  },
  {
    slug: '3-of-pentacles',
    name: '3 of Pentacles',
    meaning: 'Teamwork, skill recognition, craftsmanship collaboration',
    aerialConnection: 'two people working together to embody teamwork and collaboration , difficult pose for skill and craftsmanship, grey for structure and foundation',
    journalingPrompt: 'Where in your work or creative life would collaboration produce something neither of you could build alone?',
    artReady: false,
  },
  {
    slug: '4-of-pentacles',
    name: '4 of Pentacles',
    meaning: 'Holding tight, security, possessiveness, conservation',
    aerialConnection: 'Position and expression to depict control, holding tight for security, red for passion and materiality',
    journalingPrompt: 'What are you holding onto so tightly that your grip is preventing it from growing?',
    artReady: false,
  },
  {
    slug: '5-of-pentacles',
    name: '5 of Pentacles',
    meaning: 'Hardship, poverty, exclusion, material/spiritual crisis',
    aerialConnection: 'Bandaged Men struggling in foreground to show poverty and hardship, pole position to depict struggle, yellow for hope, red for drained vitality',
    journalingPrompt: 'Where do you feel most lacking right now, and what support is available that you have not yet allowed yourself to ask for?',
    artReady: false,
  },
  {
    slug: '6-of-pentacles',
    name: '6 of Pentacles',
    meaning: 'Generosity, charity, giving and receiving, balanced exchange',
    aerialConnection: 'splits to represent balance, gold for wealth and status',
    journalingPrompt: 'Where in your life is giving and receiving in balance, and where has generosity become a way to avoid your own needs?',
    artReady: false,
  },
  {
    slug: '7-of-pentacles',
    name: '7 of Pentacles',
    meaning: 'Patience, long-term view, assessment of progress, cultivation',
    aerialConnection: 'Position representing patience and endurance, flower crown and green skirt depicting hard work',
    journalingPrompt: 'What long-term effort are you tending right now, and do you trust that it will bear fruit if you keep showing up?',
    artReady: false,
  },
  {
    slug: '8-of-pentacles',
    name: '8 of Pentacles',
    meaning: 'Dedication, craftsmanship, skill development, diligent work',
    aerialConnection: 'Position to show skill from hard work, blue represents thoughtfullness and dedication to a skill',
    journalingPrompt: 'What skill are you genuinely committed to developing, and what does mastery actually mean to you?',
    artReady: false,
  },
  {
    slug: '9-of-pentacles',
    name: '9 of Pentacles',
    meaning: 'Independence, self-sufficiency, luxury, accomplishment achieved',
    aerialConnection: 'silver symbolizes feminine energy and fertility, pentacles surrounding figure as enjoying the fruits of her labor',
    journalingPrompt: 'What have you built entirely through your own effort that you are not fully allowing yourself to enjoy?',
    artReady: false,
  },
  {
    slug: '10-of-pentacles',
    name: '10 of Pentacles',
    meaning: 'Legacy, wealth, family, inheritance, lasting security',
    aerialConnection: 'Group of loved ones sharing wealth, lasting friendship and security, dog symbolizes companionship,',
    journalingPrompt: 'What kind of legacy are you building with your daily choices, and is it the one you actually want to leave?',
    artReady: false,
  },
  {
    slug: 'page-of-pentacles',
    name: 'Page of Pentacles',
    meaning: 'Practical learning, new financial venture, studious approach, manifestation begins',
    aerialConnection: 'red for passion energy, position for grounded practical energy',
    journalingPrompt: 'What practical skill or venture are you just beginning to cultivate, and what would committed study make possible?',
    artReady: false,
  },
  {
    slug: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    meaning: 'Reliability, hard work, methodical progress, responsible action, steady routine',
    aerialConnection: 'position for grounded and stable energy, red for passion, blue for clarity of purpose, armor for strength, black for protection and stability',
    journalingPrompt: 'Where is your steadiness and reliability your greatest strength, and where might it be keeping you from taking a necessary leap?',
    artReady: false,
  },
  {
    slug: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    meaning: 'Practical nurturing, financial security, down-to-earth wisdom, generous abundance',
    aerialConnection: 'pink for compassion and nurturing, standing pose for stability, white rabbit for nurturing connection with nature',
    journalingPrompt: 'How are you nurturing both your material world and the people you love, and where does that care need to also turn inward?',
    artReady: false,
  },
  {
    slug: 'king-of-pentacles',
    name: 'King of Pentacles',
    meaning: 'Material mastery, business success, abundance, reliable provider, Midas touch',
    aerialConnection: 'red for power a,d luxury, stable pose for mastery, pentacle in hand for abundance and wealth',
    journalingPrompt: 'What does true abundance mean to you beyond money, and how are you actively tending it in your daily life?',
    artReady: false,
  },
];

export const TOTAL_CARDS = CARDS.length;
